-- Migration: Add ~65 pan-India architecture college rows (non-Kerala primary)
-- Coverage: 18 states/UTs, all COA-approved
-- Sources: NIRF 2024 Architecture Rankings (nirfindia.org), Council of Architecture (coa.gov.in), official college websites
-- Idempotent: uses ON CONFLICT (slug) DO NOTHING

INSERT INTO colleges (
  name, slug, short_name,
  state, state_slug, city, city_slug,
  type, established_year,
  accepted_exams, courses_offered,
  total_barch_seats, annual_fee_approx, nirf_rank_architecture, nirf_year,
  website, coa_approved,
  neram_tier, is_active, verified,
  data_source, data_completeness,
  contact_status, outreach_count
) VALUES

-- MAHARASHTRA (9 - VNIT Nagpur already exists)
('Sir J.J. College of Architecture', 'sir-jj-architecture', 'Sir JJ',
 'Maharashtra', 'maharashtra', 'Mumbai', 'mumbai',
 'Government', 1913,
 ARRAY['NATA','MHT-CET','JEE Main'], ARRAY['B.Arch','M.Arch'],
 74, 25000, NULL, NULL,
 'https://sirjjcollegeofarchitecture.com', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Rachana Sansad Academy of Architecture', 'rachana-sansad-architecture', 'Rachana Sansad',
 'Maharashtra', 'maharashtra', 'Mumbai', 'mumbai',
 'Private', 1955,
 ARRAY['NATA'], ARRAY['B.Arch','M.Arch'],
 100, 197000, NULL, NULL,
 'https://rachanasansad.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Pillai HOC College of Architecture', 'pillai-hoc-architecture', 'Pillai HOC',
 'Maharashtra', 'maharashtra', 'Rasayani', 'rasayani',
 'Private', 2002,
 ARRAY['NATA','MHT-CET'], ARRAY['B.Arch'],
 40, 145000, NULL, NULL,
 'https://mahss.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Dr. D.Y. Patil College of Architecture', 'dy-patil-architecture', 'DY Patil',
 'Maharashtra', 'maharashtra', 'Pune', 'pune',
 'Private', 2007,
 ARRAY['NATA','MHT-CET'], ARRAY['B.Arch'],
 80, 200000, NULL, NULL,
 'https://dypatil.edu', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Bharati Vidyapeeth College of Architecture', 'bharati-vidyapeeth-architecture', 'BVP',
 'Maharashtra', 'maharashtra', 'Pune', 'pune',
 'Deemed', 1990,
 ARRAY['NATA','MHT-CET'], ARRAY['B.Arch','M.Arch'],
 80, 175000, NULL, NULL,
 'https://bharatividyapeeth.edu', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('MIT World Peace University School of Architecture', 'mit-wpu-architecture', 'MIT-WPU',
 'Maharashtra', 'maharashtra', 'Pune', 'pune',
 'Private', 1983,
 ARRAY['NATA','MHT-CET','JEE Main'], ARRAY['B.Arch','M.Arch'],
 80, 290000, NULL, NULL,
 'https://mitwpu.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('VITs Padmabhushan Dr Vasantdada Patil College of Architecture', 'pvp-pune-architecture', 'PVPCOA',
 'Maharashtra', 'maharashtra', 'Pune', 'pune',
 'Private', 1992,
 ARRAY['NATA','MHT-CET'], ARRAY['B.Arch'],
 80, 147000, NULL, NULL,
 'https://pvpcoapune.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Marathwada Mitra Mandals College of Architecture', 'mmcoa-architecture', 'MMCOA',
 'Maharashtra', 'maharashtra', 'Pune', 'pune',
 'Private', 1991,
 ARRAY['NATA','MHT-CET'], ARRAY['B.Arch'],
 80, 165000, NULL, NULL,
 'https://mmcoa.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('L.S. Raheja School of Architecture', 'ls-raheja-architecture', 'LSRSA',
 'Maharashtra', 'maharashtra', 'Mumbai', 'mumbai',
 'Private', 1955,
 ARRAY['NATA','MHT-CET'], ARRAY['B.Arch'],
 80, 200000, NULL, NULL,
 'https://lsraheja.org', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- KARNATAKA (5 - M.S. Ramaiah, Dayananda Sagar, Christ already exist)
('BMS College of Architecture', 'bms-coa-architecture', 'BMSCA',
 'Karnataka', 'karnataka', 'Bangalore', 'bangalore',
 'Private', 1946,
 ARRAY['NATA','KCET'], ARRAY['B.Arch','M.Arch'],
 80, 200000, 23, 2024,
 'https://bmsca.org', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('R.V. College of Architecture', 'rv-coa-architecture', 'RVCA',
 'Karnataka', 'karnataka', 'Bangalore', 'bangalore',
 'Private', 1992,
 ARRAY['NATA','KCET'], ARRAY['B.Arch','M.Arch'],
 80, 250000, NULL, NULL,
 'https://rvca.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Manipal School of Architecture and Planning', 'manipal-msap-architecture', 'MSAP',
 'Karnataka', 'karnataka', 'Manipal', 'manipal',
 'Deemed', 1978,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch','M.Plan','PhD'],
 80, 350000, 28, 2024,
 'https://manipal.edu/msap', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('KLE Technological University School of Architecture', 'kle-tech-architecture', 'KLE Tech',
 'Karnataka', 'karnataka', 'Hubli', 'hubli',
 'Private', 1947,
 ARRAY['NATA','KCET'], ARRAY['B.Arch','M.Arch'],
 80, 200000, NULL, NULL,
 'https://kletech.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('BMS School of Architecture', 'bms-soa-architecture', 'BMSSA',
 'Karnataka', 'karnataka', 'Bangalore', 'bangalore',
 'Private', 2002,
 ARRAY['NATA','KCET'], ARRAY['B.Arch'],
 80, 200000, NULL, NULL,
 'https://bmsa.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- DELHI (4 - SPA Delhi already exists)
('Jamia Millia Islamia Faculty of Architecture', 'jamia-millia-architecture', 'Jamia Millia',
 'Delhi', 'delhi', 'New Delhi', 'new-delhi',
 'Government', 1920,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch','M.Plan','PhD'],
 80, 19325, 7, 2024,
 'https://jmi.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Guru Gobind Singh Indraprastha University', 'ggsipu-architecture', 'GGSIPU',
 'Delhi', 'delhi', 'New Delhi', 'new-delhi',
 'Government', 1998,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch'],
 80, 60000, 29, 2024,
 'https://ipu.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Sushant University School of Architecture', 'sushant-architecture', 'Sushant',
 'Haryana', 'haryana', 'Gurugram', 'gurugram',
 'Private', 2012,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch','M.Plan'],
 80, 520200, NULL, NULL,
 'https://sushantuniversity.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Amity School of Architecture Noida', 'amity-noida-architecture', 'Amity Noida',
 'Uttar Pradesh', 'uttar-pradesh', 'Noida', 'noida',
 'Private', 2003,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch','M.Plan','PhD'],
 120, 126000, NULL, NULL,
 'https://amity.edu', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- HARYANA (2 - Sushant counted above is technically in Gurugram which is Haryana)
('DCRUST Murthal School of Architecture', 'dcrust-architecture', 'DCRUST',
 'Haryana', 'haryana', 'Sonipat', 'sonipat',
 'Government', 2006,
 ARRAY['JEE Main','NATA'], ARRAY['B.Arch'],
 40, 75000, NULL, NULL,
 'https://dcrustm.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('GD Goenka University School of Architecture', 'gd-goenka-architecture', 'GD Goenka',
 'Haryana', 'haryana', 'Gurugram', 'gurugram',
 'Private', 2013,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch'],
 60, 500000, NULL, NULL,
 'https://gdgoenkauniversity.com', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Manav Rachna University School of Architecture', 'manav-rachna-architecture', 'Manav Rachna',
 'Haryana', 'haryana', 'Faridabad', 'faridabad',
 'Private', 2014,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch'],
 60, 215500, NULL, NULL,
 'https://manavrachna.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- PUNJAB + CHANDIGARH (4)
('Chandigarh College of Architecture', 'cca-chandigarh-architecture', 'CCA',
 'Chandigarh', 'chandigarh', 'Chandigarh', 'chandigarh',
 'Government', 1961,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch'],
 60, 50000, 30, 2024,
 'https://cca.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Chandigarh University Department of Architecture', 'chandigarh-university-architecture', 'CU',
 'Punjab', 'punjab', 'Mohali', 'mohali',
 'Private', 2012,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch'],
 120, 165000, 13, 2024,
 'https://cuchd.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Lovely Professional University School of Architecture', 'lpu-architecture', 'LPU',
 'Punjab', 'punjab', 'Phagwara', 'phagwara',
 'Private', 2005,
 ARRAY['NATA','JEE Main','LPUNEST'], ARRAY['B.Arch','M.Arch'],
 120, 165000, 24, 2024,
 'https://lpu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Guru Nanak Dev University Department of Architecture', 'gndu-architecture', 'GNDU',
 'Punjab', 'punjab', 'Amritsar', 'amritsar',
 'Government', 1969,
 ARRAY['NATA'], ARRAY['B.Arch'],
 40, 35000, NULL, NULL,
 'https://gndu.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- RAJASTHAN (4)
('Malaviya National Institute of Technology Jaipur', 'mnit-jaipur-architecture', 'MNIT Jaipur',
 'Rajasthan', 'rajasthan', 'Jaipur', 'jaipur',
 'Government', 1963,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch','M.Plan','PhD'],
 40, 174200, 15, 2024,
 'https://mnit.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Manipal University Jaipur School of Architecture', 'manipal-jaipur-architecture', 'MUJ',
 'Rajasthan', 'rajasthan', 'Jaipur', 'jaipur',
 'Private', 2011,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch'],
 80, 320000, NULL, NULL,
 'https://jaipur.manipal.edu', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Aayojan School of Architecture', 'aayojan-architecture', 'Aayojan',
 'Rajasthan', 'rajasthan', 'Jaipur', 'jaipur',
 'Private', 1999,
 ARRAY['NATA'], ARRAY['B.Arch'],
 80, 200000, NULL, NULL,
 'https://aayojansa.com', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Poornima University School of Architecture', 'poornima-architecture', 'Poornima',
 'Rajasthan', 'rajasthan', 'Jaipur', 'jaipur',
 'Private', 2012,
 ARRAY['NATA'], ARRAY['B.Arch'],
 40, 175000, NULL, NULL,
 'https://poornima.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- UTTAR PRADESH (4 - Amity Noida counted above is technically UP)
('Indian Institute of Technology BHU Varanasi', 'iit-bhu-architecture', 'IIT BHU',
 'Uttar Pradesh', 'uttar-pradesh', 'Varanasi', 'varanasi',
 'Government', 1919,
 ARRAY['JEE Advanced','AAT'], ARRAY['B.Arch','M.Arch','M.Plan','PhD'],
 22, 250000, NULL, NULL,
 'https://iitbhu.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Aligarh Muslim University Department of Architecture', 'amu-aligarh-architecture', 'AMU',
 'Uttar Pradesh', 'uttar-pradesh', 'Aligarh', 'aligarh',
 'Government', 1920,
 ARRAY['AMU Entrance','NATA'], ARRAY['B.Arch','M.Arch','M.Plan'],
 40, 23500, 14, 2024,
 'https://amu.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Integral University Faculty of Architecture', 'integral-architecture', 'Integral',
 'Uttar Pradesh', 'uttar-pradesh', 'Lucknow', 'lucknow',
 'Private', 1998,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch'],
 80, 110000, NULL, NULL,
 'https://iul.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Gautam Buddha University School of Architecture and Planning', 'gbu-architecture', 'GBU',
 'Uttar Pradesh', 'uttar-pradesh', 'Greater Noida', 'greater-noida',
 'Government', 2008,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch','M.Plan'],
 60, 222500, NULL, NULL,
 'https://gbu.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Babu Banarasi Das University School of Architecture', 'bbdu-architecture', 'BBDU',
 'Uttar Pradesh', 'uttar-pradesh', 'Lucknow', 'lucknow',
 'Private', 2010,
 ARRAY['NATA','JEE Main','UPSEE'], ARRAY['B.Arch','M.Arch'],
 80, 150000, NULL, NULL,
 'https://bbdu.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- MADHYA PRADESH (3 - SPA Bhopal already exists)
('Maulana Azad National Institute of Technology Bhopal', 'manit-bhopal-architecture', 'MANIT Bhopal',
 'Madhya Pradesh', 'madhya-pradesh', 'Bhopal', 'bhopal',
 'Government', 1960,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch','M.Plan','PhD'],
 40, 141000, 17, 2024,
 'https://manit.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('IPS Academy School of Architecture', 'ips-indore-architecture', 'IPS Academy',
 'Madhya Pradesh', 'madhya-pradesh', 'Indore', 'indore',
 'Private', 2008,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch'],
 60, 145000, NULL, NULL,
 'https://ipsacademy.org', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('LNCT University School of Architecture', 'lnct-architecture', 'LNCT',
 'Madhya Pradesh', 'madhya-pradesh', 'Bhopal', 'bhopal',
 'Private', 2010,
 ARRAY['NATA','JEE Main','MP CET'], ARRAY['B.Arch'],
 40, 100000, NULL, NULL,
 'https://lnctuniversity.com', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- GUJARAT (3 - CEPT already exists)
('Nirma University Institute of Architecture and Planning', 'nirma-architecture', 'Nirma',
 'Gujarat', 'gujarat', 'Ahmedabad', 'ahmedabad',
 'Private', 2014,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch'],
 80, 195000, 19, 2024,
 'https://nirmauni.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Sarvajanik College of Engineering and Technology', 'scet-surat-architecture', 'SCET',
 'Gujarat', 'gujarat', 'Surat', 'surat',
 'Private', 1994,
 ARRAY['NATA','GUJCET'], ARRAY['B.Arch'],
 80, 70000, NULL, NULL,
 'https://scet.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Anant National University', 'anant-architecture', 'AnantU',
 'Gujarat', 'gujarat', 'Ahmedabad', 'ahmedabad',
 'Private', 2016,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch'],
 120, 290000, NULL, NULL,
 'https://anu.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- ANDHRA PRADESH (3 - SPA Vijayawada already exists)
('JNTU Kakinada University College of Engineering', 'jntu-kakinada-architecture', 'JNTUK',
 'Andhra Pradesh', 'andhra-pradesh', 'Kakinada', 'kakinada',
 'Government', 1946,
 ARRAY['AP EAPCET','JEE Main','NATA'], ARRAY['B.Arch'],
 40, 50000, NULL, NULL,
 'https://jntuk.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Andhra University College of Engineering Department of Architecture', 'andhra-university-architecture', 'AU',
 'Andhra Pradesh', 'andhra-pradesh', 'Visakhapatnam', 'visakhapatnam',
 'Government', 1955,
 ARRAY['AP EAPCET','JEE Main'], ARRAY['B.Arch','M.Arch'],
 30, 35000, NULL, NULL,
 'https://andhrauniversity.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('GITAM School of Architecture', 'gitam-architecture', 'GITAM',
 'Andhra Pradesh', 'andhra-pradesh', 'Visakhapatnam', 'visakhapatnam',
 'Deemed', 2009,
 ARRAY['NATA','JEE Main','GAT'], ARRAY['B.Arch'],
 60, 250000, NULL, NULL,
 'https://gitam.edu', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- TELANGANA (4)
('JNTU Hyderabad School of Planning and Architecture', 'jntu-hyderabad-architecture', 'JNTU-H',
 'Telangana', 'telangana', 'Hyderabad', 'hyderabad',
 'Government', 1972,
 ARRAY['TS EAMCET','JEE Main','NATA'], ARRAY['B.Arch','M.Arch','M.Plan','PhD'],
 40, 45000, NULL, NULL,
 'https://jntuh.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Auroras Design Academy', 'aurora-design-architecture', 'ADA',
 'Telangana', 'telangana', 'Hyderabad', 'hyderabad',
 'Private', 2007,
 ARRAY['NATA','TS EAMCET'], ARRAY['B.Arch'],
 60, 120000, NULL, NULL,
 'https://adastudy.org', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Vasavi College of Engineering Department of Architecture', 'vasavi-architecture', 'Vasavi',
 'Telangana', 'telangana', 'Hyderabad', 'hyderabad',
 'Private', 1981,
 ARRAY['NATA','TS EAMCET'], ARRAY['B.Arch'],
 40, 130000, NULL, NULL,
 'https://vce.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('BRS Architecture College', 'brs-hyderabad-architecture', 'BRS',
 'Telangana', 'telangana', 'Hyderabad', 'hyderabad',
 'Private', 2008,
 ARRAY['NATA','TS EAMCET'], ARRAY['B.Arch'],
 40, 100000, NULL, NULL,
 'https://brsarchitecture.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- WEST BENGAL (5)
('Indian Institute of Technology Kharagpur', 'iit-kharagpur-architecture', 'IIT Kharagpur',
 'West Bengal', 'west-bengal', 'Kharagpur', 'kharagpur',
 'Government', 1951,
 ARRAY['JEE Advanced','AAT'], ARRAY['B.Arch','M.Arch','M.Plan','PhD'],
 35, 250000, 2, 2024,
 'https://iitkgp.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Indian Institute of Engineering Science and Technology Shibpur', 'iiest-shibpur-architecture', 'IIEST Shibpur',
 'West Bengal', 'west-bengal', 'Howrah', 'howrah',
 'Government', 1856,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch','M.Plan','PhD'],
 40, 135400, 4, 2024,
 'https://iiests.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Jadavpur University Department of Architecture', 'jadavpur-architecture', 'JU',
 'West Bengal', 'west-bengal', 'Kolkata', 'kolkata',
 'Government', 1955,
 ARRAY['WBJEE','JEE Main'], ARRAY['B.Arch','M.Arch','M.Plan'],
 38, 4800, NULL, NULL,
 'https://jaduniv.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Amity University Kolkata School of Architecture', 'amity-kolkata-architecture', 'Amity Kolkata',
 'West Bengal', 'west-bengal', 'Kolkata', 'kolkata',
 'Private', 2014,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch','M.Arch'],
 60, 280000, 25, 2024,
 'https://amity.edu/kolkata', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Brainware University School of Architecture', 'brainware-architecture', 'Brainware',
 'West Bengal', 'west-bengal', 'Kolkata', 'kolkata',
 'Private', 2016,
 ARRAY['NATA','WBJEE'], ARRAY['B.Arch'],
 40, 130000, NULL, NULL,
 'https://brainwareuniversity.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- ODISHA (3)
('National Institute of Technology Rourkela Department of Architecture', 'nit-rourkela-architecture', 'NIT Rourkela',
 'Odisha', 'odisha', 'Rourkela', 'rourkela',
 'Government', 1981,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch','PhD'],
 40, 152200, 9, 2024,
 'https://nitrkl.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('KIIT School of Architecture', 'kiit-architecture', 'KIIT SoA',
 'Odisha', 'odisha', 'Bhubaneswar', 'bhubaneswar',
 'Deemed', 2008,
 ARRAY['NATA','JEE Main','KIITEE'], ARRAY['B.Arch','M.Arch'],
 80, 320000, NULL, NULL,
 'https://kiit.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('College of Engineering and Technology Bhubaneswar', 'cet-bhubaneswar-architecture', 'CET BBSR',
 'Odisha', 'odisha', 'Bhubaneswar', 'bhubaneswar',
 'Government', 1981,
 ARRAY['OJEE','JEE Main','NATA'], ARRAY['B.Arch','M.Arch','M.Plan'],
 40, 80000, NULL, NULL,
 'https://cet.edu.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- BIHAR + JHARKHAND (2)
('National Institute of Technology Patna Department of Architecture', 'nit-patna-architecture', 'NIT Patna',
 'Bihar', 'bihar', 'Patna', 'patna',
 'Government', 1986,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch','PhD'],
 40, 145000, 27, 2024,
 'https://nitp.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('Birla Institute of Technology Mesra Department of Architecture', 'bit-mesra-architecture', 'BIT Mesra',
 'Jharkhand', 'jharkhand', 'Ranchi', 'ranchi',
 'Deemed', 1955,
 ARRAY['JEE Main','BITSAT'], ARRAY['B.Arch','M.Arch'],
 60, 343000, 20, 2024,
 'https://bitmesra.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

-- CHHATTISGARH (2)
('National Institute of Technology Raipur Department of Architecture', 'nit-raipur-architecture', 'NIT Raipur',
 'Chhattisgarh', 'chhattisgarh', 'Raipur', 'raipur',
 'Government', 1956,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch'],
 40, 144000, NULL, NULL,
 'https://nitrr.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Kalinga University Faculty of Architecture', 'kalinga-architecture', 'Kalinga',
 'Chhattisgarh', 'chhattisgarh', 'Raipur', 'raipur',
 'Private', 2011,
 ARRAY['NATA','CG PET'], ARRAY['B.Arch'],
 40, 110000, NULL, NULL,
 'https://kalingauniversity.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- ASSAM + NORTHEAST (2)
('Royal Global University School of Architecture', 'royal-global-architecture', 'RGU',
 'Assam', 'assam', 'Guwahati', 'guwahati',
 'Private', 2009,
 ARRAY['NATA'], ARRAY['B.Arch','M.Arch'],
 60, 200000, NULL, NULL,
 'https://rgu.ac', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('North Eastern Hill University Department of Architecture', 'nehu-shillong-architecture', 'NEHU',
 'Meghalaya', 'meghalaya', 'Shillong', 'shillong',
 'Government', 1973,
 ARRAY['NATA','JEE Main'], ARRAY['B.Arch'],
 30, 30000, NULL, NULL,
 'https://nehu.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- GOA (1)
('Goa College of Architecture', 'goa-coa-architecture', 'GCA',
 'Goa', 'goa', 'Panaji', 'panaji',
 'Government', 1982,
 ARRAY['NATA'], ARRAY['B.Arch','M.Arch'],
 60, 60800, NULL, NULL,
 'https://gcarch.goa.gov.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- HIMACHAL PRADESH + UTTARAKHAND (2)
('National Institute of Technology Hamirpur Department of Architecture', 'nit-hamirpur-architecture', 'NIT Hamirpur',
 'Himachal Pradesh', 'himachal-pradesh', 'Hamirpur', 'hamirpur',
 'Government', 2000,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch'],
 40, 125000, NULL, NULL,
 'https://nith.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

('Indian Institute of Technology Roorkee Department of Architecture and Planning', 'iit-roorkee-architecture', 'IIT Roorkee',
 'Uttarakhand', 'uttarakhand', 'Roorkee', 'roorkee',
 'Government', 1856,
 ARRAY['JEE Advanced','AAT'], ARRAY['B.Arch','M.Arch','M.Plan','PhD'],
 25, 250000, 1, 2024,
 'https://iitr.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

-- J&K (1)
('National Institute of Technology Srinagar Department of Architecture', 'nit-srinagar-architecture', 'NIT Srinagar',
 'Jammu and Kashmir', 'jammu-and-kashmir', 'Srinagar', 'srinagar',
 'Government', 1960,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch'],
 40, 125000, NULL, NULL,
 'https://nitsri.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 91, 'never_contacted', 0),

-- KERALA (2 - top NIRF; KEAM batch is in separate migration)
('National Institute of Technology Calicut Department of Architecture', 'nit-calicut-architecture', 'NIT Calicut',
 'Kerala', 'kerala', 'Kozhikode', 'kozhikode',
 'Government', 1961,
 ARRAY['JEE Main'], ARRAY['B.Arch','M.Arch'],
 40, 145000, 3, 2024,
 'https://nitc.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0),

('College of Engineering Trivandrum Department of Architecture', 'cet-trivandrum-architecture', 'CET Trivandrum',
 'Kerala', 'kerala', 'Thiruvananthapuram', 'thiruvananthapuram',
 'Government', 1939,
 ARRAY['KEAM','JEE Main','NATA'], ARRAY['B.Arch','M.Arch'],
 30, 25000, 18, 2024,
 'https://cet.ac.in', TRUE,
 'free', TRUE, FALSE, 'pan_india_research_2026_05', 100, 'never_contacted', 0)

ON CONFLICT (slug) DO NOTHING;
