-- Seed aintra_knowledge_base with architecture admissions Q&A entries.
-- Idempotent: each row is inserted only if no matching (question, category)
-- pair already exists. Does not require a unique constraint (existing prod
-- data has duplicate pairs in other categories, so we avoid depending on one).
-- Admin-editable via Supabase dashboard; route.ts cache picks up changes within 5 min.

INSERT INTO public.aintra_knowledge_base (question, answer, category, is_active, display_order)
SELECT v.question, v.answer, v.category, v.is_active, v.display_order
FROM (VALUES
  ('What is the NATA 2026 exam pattern?', 'NATA 2026 has two parts: Part A (Drawing, 80 marks, offline paper) and Part B (MCQ/NCQ, 120 marks, online adaptive). Total 200 marks over 3 hours. No negative marking and no minimum qualifying score. Conducted by the Council of Architecture (CoA).', 'Architecture Admissions', true, 100),
  ('When is NATA 2026?', 'NATA 2026 is conducted in two phases. Phase 1 runs April 4 to June 13, 2026 (up to 2 attempts, percentile scoring). Phase 2 is on August 7 and 8, 2026 (single attempt, raw scores). Candidates can appear in only one phase. Register at www.nata.in.', 'Architecture Admissions', true, 101),
  ('How does TNEA architecture counseling work?', 'Tamil Nadu architecture seats are allotted through TNEA (tneaonline.org). Steps: (1) online registration, (2) random number and rank list, (3) choice filling for college and branch preferences, (4) allotment rounds (government and self-financing), (5) reporting at the allotted college. A valid NATA score is required.', 'Architecture Admissions', true, 102),
  ('What is the Kerala architecture admission process?', 'Kerala admits through KEAM + Centralized Allotment Process (CAP) by CEE Kerala. A separate architecture rank list is published based on NATA score combined with 10+2 marks. Allotment happens in multiple rounds.', 'Architecture Admissions', true, 103),
  ('What is the Karnataka architecture admission process?', 'Karnataka uses KCET for government and aided seats and COMEDK for private self-financing seats. NATA is required for B.Arch admission regardless of the counseling route. Admissions are managed by KEA (Karnataka Examinations Authority).', 'Architecture Admissions', true, 104),
  ('What does COA approval mean?', 'The Council of Architecture (CoA) is the statutory body regulating architecture education in India. A COA-approved program is mandatory to register and practice as an architect. Always check COA approval before joining any B.Arch program, no approval means the degree will not qualify you to practice.', 'Architecture Admissions', true, 105),
  ('What is NAAC grade and why does it matter?', 'NAAC (National Assessment and Accreditation Council) grades institutions A++, A+, A, B++, B+, B based on peer review of teaching, research, infrastructure, and outcomes. Higher NAAC grades generally signal better institutional quality. It is a supporting signal, not a substitute for COA approval.', 'Architecture Admissions', true, 106),
  ('What is NIRF ranking?', 'NIRF (National Institutional Ranking Framework) is the Ministry of Education annual ranking. It ranks institutions on teaching, research, graduation outcomes, outreach, and perception. For architecture specifically, look at the Architecture discipline ranking rather than the overall rank.', 'Architecture Admissions', true, 107),
  ('What is the difference between B.Arch and B.Planning?', 'B.Arch is a 5-year professional degree focused on design, construction, and aesthetics, it licenses you to practice as an architect (after COA registration). B.Planning is a 4-year degree focused on urban and regional planning, careers include town planning, GIS analysis, and policy. Fewer colleges offer B.Planning.', 'Architecture Admissions', true, 108),
  ('Are there scholarships for architecture students?', 'Yes. Most states offer merit, SC/ST/OBC, and minority scholarships administered through the state scholarship portal. Many private colleges offer their own merit-based concessions. Neram Classes also offers performance-based scholarships for coaching, details at neramclasses.com/scholarship.', 'Architecture Admissions', true, 109),
  ('How is architecture college fee structured?', 'Annual fees typically include tuition (the main component), hostel (if residential), mess, lab/studio fees, library and caution deposit. Government colleges charge around 30k to 80k per year. Self-financing and deemed colleges range from 1L to 3L+. Always check the full 5-year cost, not just Year 1.', 'Architecture Admissions', true, 110),
  ('What are the career paths after B.Arch?', 'Common paths: practising architect (register with CoA), urban designer, interior designer, landscape architect, BIM/CAD specialist, construction manager, sustainability consultant, academia, or higher studies (M.Arch, MBA, urban planning abroad). Many also go into real estate, architectural journalism, or product design.', 'Architecture Admissions', true, 111),
  ('How do I shortlist architecture colleges?', 'A practical shortlist: (1) filter to COA-approved colleges, (2) confirm NATA or JEE Paper 2 eligibility matches your exam plan, (3) check NAAC grade or NIRF rank for quality signal, (4) compare 5-year total fees against your budget, (5) check placements and top recruiters if available, (6) consider location and hostel availability. Neram college hub shows all these at a glance.', 'Architecture Admissions', true, 112),
  ('JEE Paper 2 or NATA, which one should I take?', 'Both accept students into B.Arch, but the college set differs. NITs, SPAs (Schools of Planning and Architecture), and IIITs admit through JEE Paper 2 (JoSAA counseling). Most state colleges and private colleges accept NATA. Many students take both to maximize options. Check each target college accepted_exams list.', 'Architecture Admissions', true, 113),
  ('Who accepts KCET for architecture?', 'KCET is used by government and aided colleges in Karnataka. Private colleges in Karnataka typically use COMEDK or management quota. In both cases NATA is required for B.Arch admission.', 'Architecture Admissions', true, 114)
) AS v(question, answer, category, is_active, display_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.aintra_knowledge_base kb
  WHERE kb.question = v.question AND kb.category = v.category
);
