-- Migration: Add 18 new architecture college rows for AskSeniors feature
-- Excludes SRM, VIT Vellore, Christ University (already inserted as paid clients)
-- Uses ON CONFLICT DO NOTHING to be idempotent (safe to re-run)

INSERT INTO colleges (
  name,
  slug,
  state,
  state_slug,
  city,
  short_name,
  type,
  coa_approved,
  accepted_exams,
  neram_tier,
  logo_url,
  verified,
  is_active,
  contact_status,
  outreach_count
) VALUES
  (
    'Anna University',
    'anna-university-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Chennai',
    'Anna University',
    'Government',
    TRUE,
    ARRAY['TNEA', 'NATA', 'JEE Main'],
    'tier-1',
    '/images/ask-seniors/colleges/Anna_University_Logo.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'National Institute of Technology Trichy',
    'nit-trichy-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Tiruchirappalli',
    'NIT Trichy',
    'Government',
    TRUE,
    ARRAY['JEE Main', 'NATA'],
    'tier-1',
    '/images/ask-seniors/colleges/National_Institute_of_Technology_Trichy_Logo.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'PSG College of Technology',
    'psg-college-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Coimbatore',
    'PSG',
    'Private',
    TRUE,
    ARRAY['TNEA', 'NATA'],
    'tier-1',
    '/images/ask-seniors/colleges/PSG_IAP_coimbatore.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'School of Planning and Architecture Delhi',
    'spa-delhi-architecture',
    'Delhi',
    'delhi',
    'New Delhi',
    'SPA Delhi',
    'Government',
    TRUE,
    ARRAY['NATA', 'JEE Main'],
    'tier-1',
    '/images/ask-seniors/colleges/SPA_Delhi.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'CEPT University',
    'cept-university-architecture',
    'Gujarat',
    'gujarat',
    'Ahmedabad',
    'CEPT',
    'Private',
    TRUE,
    ARRAY['NATA', 'JEE Main'],
    'tier-1',
    '/images/ask-seniors/colleges/Cept_Ahmedaba.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'MEASI Academy of Architecture',
    'measi-academy-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Chennai',
    'MEASI',
    'Private',
    TRUE,
    ARRAY['TNEA', 'NATA'],
    'tier-2',
    '/images/ask-seniors/colleges/MEASI_chennai.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'M.S. Ramaiah University of Applied Sciences',
    'ms-ramaiah-architecture',
    'Karnataka',
    'karnataka',
    'Bangalore',
    'MS Ramaiah',
    'Private',
    TRUE,
    ARRAY['NATA', 'JEE Main'],
    'tier-1',
    '/images/ask-seniors/colleges/ms_Ramaiah_bangalore.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'Dayananda Sagar University',
    'dayananda-sagar-architecture',
    'Karnataka',
    'karnataka',
    'Bangalore',
    'DSU',
    'Private',
    TRUE,
    ARRAY['NATA', 'JEE Main'],
    'tier-2',
    '/images/ask-seniors/colleges/DSU.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'School of Planning and Architecture Bhopal',
    'spa-bhopal-architecture',
    'Madhya Pradesh',
    'madhya-pradesh',
    'Bhopal',
    'SPA Bhopal',
    'Government',
    TRUE,
    ARRAY['NATA', 'JEE Main'],
    'tier-1',
    '/images/ask-seniors/colleges/SPA-Bhopal.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'Thiagarajar College of Engineering',
    'thiagarajar-college-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Madurai',
    'Thiagarajar',
    'Private',
    TRUE,
    ARRAY['TNEA', 'NATA'],
    'tier-2',
    '/images/ask-seniors/colleges/Thiagarajar_College_of_Engineering_logo_MADURAI.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'Rathinam College of Arts and Science',
    'rathinam-college-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Coimbatore',
    'Rathinam',
    'Private',
    TRUE,
    ARRAY['TNEA', 'NATA'],
    'tier-3',
    '/images/ask-seniors/colleges/Rathinam_coimbatore.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'Karpagam Academy of Higher Education',
    'karpagam-academy-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Coimbatore',
    'Karpagam',
    'Private',
    TRUE,
    ARRAY['TNEA', 'NATA'],
    'tier-3',
    '/images/ask-seniors/colleges/karpagamcollege_Coimbatore.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'Visvesvaraya National Institute of Technology Nagpur',
    'vnit-nagpur-architecture',
    'Maharashtra',
    'maharashtra',
    'Nagpur',
    'VNIT Nagpur',
    'Government',
    TRUE,
    ARRAY['JEE Main', 'NATA'],
    'tier-1',
    '/images/ask-seniors/colleges/VNIT_logo_NAGPUR.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'School of Planning and Architecture Vijayawada',
    'spa-vijayawada-architecture',
    'Andhra Pradesh',
    'andhra-pradesh',
    'Vijayawada',
    'SPA Vijayawada',
    'Government',
    TRUE,
    ARRAY['NATA', 'JEE Main'],
    'tier-1',
    '/images/ask-seniors/colleges/School_of_Planning_and_Architecture,_Vijayawada_Logo.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'McGAN''s Ooty School of Architecture',
    'mcgans-ooty-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Ooty',
    'McGAN''s Ooty',
    'Private',
    TRUE,
    ARRAY['TNEA', 'NATA'],
    'tier-3',
    '/images/ask-seniors/colleges/McGAN''S_ooty.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'PRIME College of Architecture and Planning',
    'prime-nagapattinam-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Nagapattinam',
    'PRIME',
    'Private',
    TRUE,
    ARRAY['TNEA', 'NATA'],
    'tier-3',
    '/images/ask-seniors/colleges/PRIME_Nagapattinam.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'Periyar University',
    'periyar-university-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Salem',
    'Periyar',
    'Government',
    TRUE,
    ARRAY['TNEA', 'NATA'],
    'tier-2',
    '/images/ask-seniors/colleges/periyar.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  ),
  (
    'PAPNI School of Architecture',
    'papni-architecture',
    'Tamil Nadu',
    'tamil-nadu',
    'Chennai',
    'PAPNI',
    'Private',
    TRUE,
    ARRAY['TNEA', 'NATA'],
    'tier-3',
    '/images/ask-seniors/colleges/papni.webp',
    TRUE,
    TRUE,
    'never_contacted',
    0
  )
ON CONFLICT (slug) DO NOTHING;
