-- Seed aintra_knowledge_base with AAT 2026 and PGETA 2026 Q&A entries.
-- Mirrors the idempotent pattern of 20260423090100_aintra_architecture_kb_seed.sql,
-- so re-running this migration is safe and admins can override individual rows
-- via the Supabase dashboard / admin /aintra-kb page without conflict.
--
-- Categories: 'AAT 2026', 'PGETA 2026'
-- All answers use natural punctuation only (no em-dashes), per project rule.
-- Display order range 200-211 for AAT, 212-223 for PGETA, leaving 100-199 for
-- the existing architecture-admissions seed.

INSERT INTO public.aintra_knowledge_base (question, answer, category, is_active, display_order)
SELECT v.question, v.answer, v.category, v.is_active, v.display_order
FROM (VALUES
  -- ─── AAT 2026 ──────────────────────────────────────────────────────────────
  ('What is the AAT exam?', 'AAT (Architecture Aptitude Test) is the qualifying test for B.Arch admission at IIT Roorkee, IIT Kharagpur, and IIT (BHU) Varanasi. It is conducted by the JEE (Advanced) board. Only candidates who have qualified JEE Advanced are eligible to appear in AAT. The test evaluates drawing skill, three-dimensional perception, imagination, aesthetic sensitivity, and architectural awareness.', 'AAT 2026', true, 200),
  ('Who is eligible for AAT 2026?', 'Only candidates who have qualified JEE (Advanced) 2026 are eligible to appear in AAT 2026. There is no separate eligibility criterion beyond JEE Advanced qualification. You must register for AAT through the JEE Advanced 2026 portal during the short registration window.', 'AAT 2026', true, 201),
  ('When is AAT 2026?', 'AAT 2026 is on Thursday, June 4, 2026 from 9:00 to 12:00 IST. Online registration is open Monday, June 1, 2026 at 10:00 IST to Tuesday, June 2, 2026 at 17:00 IST on the JEE (Advanced) 2026 portal at jeeadv.ac.in. Results are declared on Sunday, June 7, 2026 at 17:00 IST. Candidates must reach the examination centre by 8:00 IST on exam day.', 'AAT 2026', true, 202),
  ('What is the AAT exam pattern?', 'AAT 2026 is one offline pen-and-paper test of 3 hours. The question paper is in English only. There are no separate sections with weights publicly disclosed by JEE Advanced. The result is a Pass or Fail status decided by the Joint Implementation Committee, no marks or rank is published.', 'AAT 2026', true, 203),
  ('What is the AAT syllabus?', 'AAT 2026 covers five areas: (1) Freehand Drawing, sketching everyday objects from memory with correct proportion. (2) Geometrical Drawing, plans, elevations, and 3D form representation using a geometry box. (3) Three-Dimensional Perception, visualising volume, depth, and structure. (4) Imagination and Aesthetic Sensitivity, creative composition, colour, and contextual design. (5) Architectural Awareness, knowledge of famous buildings, architects, and design movements. The official syllabus PDF is at jeeadv.ac.in/documents/aat-syllabus.pdf.', 'AAT 2026', true, 204),
  ('Is there a separate rank or score in AAT?', 'No. AAT is a qualifying test only. Candidates are declared either Pass or Fail. There is no separate AAT rank or marksheet. B.Arch seat allotment uses the category-wise All India Rank from JEE (Advanced) 2026, and only AAT-passed candidates are considered for B.Arch.', 'AAT 2026', true, 205),
  ('Which IITs offer B.Arch through AAT?', 'Three IITs offer B.Arch admission via AAT 2026: IIT Roorkee, IIT Kharagpur, and IIT (BHU) Varanasi. Seats are allotted strictly on JEE (Advanced) All India Rank, with AAT Pass status being a non-negotiable prerequisite.', 'AAT 2026', true, 206),
  ('What drawing materials should I bring to AAT?', 'Candidates must bring their own drawing and colouring aids. Recommended: HB to 2B pencils, sharpener, soft erasers, geometry box (compass, scales, set squares, protractor), 12-15 inch ruler, and colouring aids such as colour pencils or crayons. Avoid wet paints or watercolours that risk smudging the answer sheet. Mobile phones, calculators, and electronic devices are not allowed.', 'AAT 2026', true, 207),
  ('Is there a fee for AAT 2026?', 'No. There is no separate registration fee for AAT 2026. The JEE (Advanced) 2026 fee that you already paid covers AAT. Registration is through the JEE Advanced portal and is free for all qualifiers.', 'AAT 2026', true, 208),
  ('Do I need a separate admit card for AAT?', 'No separate admit card is issued for AAT. Carry the printed JEE (Advanced) 2026 admit card along with an original government photo ID (Aadhaar, Passport, Driving License, or Voter ID) to the AAT examination hall. Without these, you will not be permitted to appear.', 'AAT 2026', true, 209),
  ('Are PwD candidates given extra time in AAT?', 'Yes. PwD candidates with at least 40% impairment under the RPwD Act 2016 are eligible for one hour of compensatory time, making AAT a 4-hour test for them. The same applies to candidates with less than 40% disability who have difficulty writing under Section 2(s) of the RPwD Act. Scribe (amanuensis) services are available, but you must request them during JEE Advanced registration via the prescribed certificate format.', 'AAT 2026', true, 210),
  ('What is the difference between AAT and NATA?', 'AAT and NATA are different exams for different colleges. AAT is for B.Arch at three IITs only and requires JEE Advanced qualification. NATA is for B.Arch at most other architecture colleges in India (state and private), conducted by the Council of Architecture, with no JEE prerequisite. AAT is offline pen-and-paper for 3 hours with Pass/Fail result. NATA has Drawing offline plus MCQ/NCQ online with marks and percentile. Many architecture aspirants take both for maximum coverage.', 'AAT 2026', true, 211),

  -- ─── PGETA 2026 ────────────────────────────────────────────────────────────
  ('What is PGETA?', 'PGETA (Post Graduate Entrance Test in Architecture), also commonly searched as PGEAT, is the unified national-level entrance test for M.Arch and other postgraduate architecture programs in India. It is conducted by the Council of Architecture (COA). PGETA replaces multiple state-level and institution-level PG entrance exams with a single window, and scores are accepted by COA-approved M.Arch institutions across the country.', 'PGETA 2026', true, 212),
  ('Who is eligible for PGETA 2026?', 'You must hold a Bachelor of Architecture (B.Arch) degree from a COA-approved institution with at least 50% aggregate marks (or equivalent CGPA). Final-year B.Arch students are also eligible to apply, with admission subject to passing their B.Arch. There is no upper age limit.', 'PGETA 2026', true, 213),
  ('When is PGETA 2026?', 'PGETA 2026 is conducted in three attempts: Test 1 on May 31, 2026, Test 2 on June 14, 2026, Test 3 on June 28, 2026. All tests run from 10:00 AM to 12:00 PM. Registration opened April 21, 2026 and final results are declared on July 7, 2026. Candidates may take up to all three attempts; the best score is retained. Each attempt requires a separate fee.', 'PGETA 2026', true, 214),
  ('What is the PGETA exam pattern?', 'PGETA 2026 is a Computer-Based Test (CBT) of 2 hours (120 minutes). The paper has 100 questions across four modules: Architecture and Design (64 questions), Building Sciences and Applied Engineering (14 questions), Professional Electives (6 questions), and Professional Ability and Skill Enhancement (16 questions). The test is conducted in English at designated centres; it is not a from-home online test.', 'PGETA 2026', true, 215),
  ('What is the PGETA fee?', 'PGETA 2026 fees per attempt: General and OBC (Non-Creamy Layer) candidates pay Rs 1,750. SC, ST, EWS, and PwD candidates pay Rs 1,250. Transgender candidates pay Rs 1,000. Payment is online via debit card, credit card, or net banking. Each of the three attempts requires a separate fee.', 'PGETA 2026', true, 216),
  ('What is the PGETA syllabus?', 'PGETA 2026 syllabus broadly covers architectural theory and history, urban design and planning, climate-responsive and sustainable design, building construction systems, building services, environmental technologies, professional practice and ethics, and research and documentation. The detailed syllabus is published in the official PGETA Information Brochure on the COA and PGETA portals.', 'PGETA 2026', true, 217),
  ('Where can I take the PGETA 2026 exam?', 'PGETA 2026 is conducted at designated CBT centres in major Indian cities including Delhi, Mumbai, Bengaluru, Chennai, Hyderabad, Ahmedabad, Lucknow, and 60+ additional cities. Candidates select preferred centre cities during registration and the final centre is allocated by the conducting body.', 'PGETA 2026', true, 218),
  ('Is PGETA the same as PGEAT?', 'Yes. PGEAT is a common informal spelling of PGETA. The official name from the Council of Architecture is PGETA (Post Graduate Entrance Test in Architecture). All references and registrations should use the PGETA name.', 'PGETA 2026', true, 219),
  ('How many institutions accept PGETA scores?', 'COA lists around 132 approved Master of Architecture programs across India (as of 2022-23) that admit through PGETA scores. Notable accepting institutions include Chandigarh College of Architecture, KRVIA Mumbai, Manipal School of Architecture and Planning, Rizvi College of Architecture, and Nirma University Institute of Architecture and Planning. The full list is on the COA approved-institutions page.', 'PGETA 2026', true, 220),
  ('Are there scholarships for PGETA top scorers?', 'Yes. The Council of Architecture offers a scholarship of Rs 50,000 over two years (Rs 25,000 per year) to the top 100 PGETA scorers. The scholarship is conditional on securing admission in a COA-approved institution and meeting academic criteria during the M.Arch program.', 'PGETA 2026', true, 221),
  ('How long is a PGETA score valid?', 'A PGETA 2026 score is valid for the 2026-2027 admission cycle. Validity beyond one cycle is at the discretion of the participating institution. Always verify with your target M.Arch program before relying on a previous-year score.', 'PGETA 2026', true, 222),
  ('What is the difference between PGETA and NATA?', 'PGETA and NATA are different COA exams for different levels. NATA is the entrance for Bachelor of Architecture (B.Arch), a 5-year undergraduate program; eligibility is class 12 pass with Mathematics. PGETA is the entrance for Master of Architecture (M.Arch), a 2-year postgraduate program; eligibility is a B.Arch degree with at least 50%. NATA emphasises drawing and design aptitude, while PGETA emphasises architectural theory, building science, and research aptitude.', 'PGETA 2026', true, 223)
) AS v(question, answer, category, is_active, display_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.aintra_knowledge_base kb
  WHERE kb.question = v.question AND kb.category = v.category
);
