-- Seed aintra_knowledge_base with TNEA B.Arch 2026 Q&A entries.
-- Source: apps/marketing/src/data/tnea-barch-2026/faqs.json
-- Idempotent: each row inserted only if no matching (question, category) pair exists.
-- Category 'tnea_barch_2026' is filtered by /api/aintra/tnea-barch route.
-- Admin-editable via Supabase dashboard; route cache picks up changes within 5 min.

INSERT INTO public.aintra_knowledge_base (question, answer, category, is_active, display_order)
SELECT v.question, v.answer, v.category, v.is_active, v.display_order
FROM (VALUES
  ('What is TNEA B.Arch Counselling?', 'TNEA B.Arch Counselling is the centralised admission process conducted by the Directorate of Technical Education, Tamil Nadu (through Anna University) for the 5-year Bachelor of Architecture programme in Anna University departments, government-aided engineering colleges, and seats surrendered by self-financing colleges in Tamil Nadu.', 'tnea_barch_2026', true, 100),
  ('What is the official TNEA B.Arch portal?', 'The official portal is https://barch.tneaonline.org (or the parent site https://www.tneaonline.org and https://www.dte.tn.gov.in). All registration, certificate upload, and counselling happens online through this portal.', 'tnea_barch_2026', true, 101),
  ('When does TNEA B.Arch 2026 registration open and close?', 'Online registration tentatively opens on 03 May 2026 and closes on 20 June 2026. Certificate upload also closes on 20 June 2026. These dates are tentative until the official notification is issued.', 'tnea_barch_2026', true, 102),
  ('What is the academic eligibility for TNEA B.Arch?', 'You must have passed 10+2 (or equivalent) with Physics and Mathematics as compulsory subjects, plus one elective from Chemistry, Biology, Computer Science, IT, Engineering Graphics, Business Studies, or a Technical Vocational subject, scoring at least 45 percent aggregate. A 10+3 Diploma with Mathematics as a compulsory subject and 45 percent aggregate is also accepted.', 'tnea_barch_2026', true, 103),
  ('Do I need NATA or JEE Paper 2 for TNEA B.Arch?', 'Yes, you need a qualifying score in NATA (conducted by the Council of Architecture) or JEE (Main) Paper-2 B.Arch (conducted by NTA). If you have both, the higher score is used in the merit calculation.', 'tnea_barch_2026', true, 104),
  ('How is the TNEA B.Arch merit score calculated?', 'Total = Board marks (out of 200) + NATA or JEE Paper-2 marks (out of 200) = 400. Board marks are scaled to 200 by (marks / max) x 200. The higher of NATA and JEE Paper-2 is used. Ties are broken by HSC aggregate, then date of birth (elder preferred), then random number assigned at registration.', 'tnea_barch_2026', true, 105),
  ('Is the best NATA score considered if I take multiple attempts?', 'Yes. Per the Council of Architecture rules followed by TNEA, the best NATA score across attempts is considered. Valid NATA 2025 scores (for candidates who did not take admission in 2025-26) are also accepted, subject to COA conditions.', 'tnea_barch_2026', true, 106),
  ('I am a Tamil Nadu native but studied 12th outside Tamil Nadu. Am I eligible?', 'Yes. You must produce a Nativity Certificate in electronic form or digitally signed e-Certificate issued by the Government of Tamil Nadu. Without it, your application will not be considered for Tamil Nadu nativity-based seats.', 'tnea_barch_2026', true, 107),
  ('I am from another state but studied 8th to 12th in Tamil Nadu. Am I eligible?', 'Yes. You do not need a Nativity Certificate. You will be considered under the Open Competition category.', 'tnea_barch_2026', true, 108),
  ('What are the reservation percentages in TNEA?', 'Open Competition 31 percent, Backward Class (BC) 26.5 percent, Backward Class Muslim (BCM) 3.5 percent, Most Backward Class and Denotified Communities (MBC and DNC) 20 percent, Scheduled Caste (SC) 15 percent, Scheduled Caste Arunthathiyars (SCA) 3 percent, Scheduled Tribe (ST) 1 percent. SC, SCA, ST, MBC, BC, BCM candidates can also compete for Open Competition seats in addition to their reserved quota.', 'tnea_barch_2026', true, 109),
  ('What is the 7.5 percent Government School quota?', '7.5 percent of seats are reserved on a preferential basis for students who studied 6th to 12th standard in a Tamil Nadu Government, Corporation, Municipal, Adi Dravidar and Tribal Welfare, Kallar Reclamation, or Forest Department school. This applies on top of all categories including Open. Tuition, hostel, and counselling fees are fully waived for selected candidates.', 'tnea_barch_2026', true, 110),
  ('Who is eligible for the First Graduate fee concession?', 'Candidates who will be the first graduate in their family. You must produce a First Graduate Certificate from the Head Quarters Deputy Tahsildar in the prescribed format, plus a joint declaration by you and your parent. If a brother or sister has already availed this concession, you are not eligible.', 'tnea_barch_2026', true, 111),
  ('What is the TNEA B.Arch registration fee?', 'Rs.500 for OC, BC, BCM, and MBC and DNC candidates. Rs.250 for SC, SCA, and ST candidates. Payment is accepted by Credit/Debit card, Net banking, UPI, or Demand Draft favouring The Secretary, TNEA payable at Chennai.', 'tnea_barch_2026', true, 112),
  ('What documents do I need to upload?', 'Key documents: 10th and 12th (or Diploma) mark sheets, NATA / JEE Paper-2 score card, Transfer Certificate, Aadhaar card, Nativity Certificate (if applicable), Permanent Community Certificate (for reserved categories), First Graduate Certificate (if claiming concession), Government School study proof for 7.5 percent quota, and special reservation certificates if applicable.', 'tnea_barch_2026', true, 113),
  ('What is a TFC and do I need to visit one?', 'A TFC (Tamil Nadu Engineering Admissions Facilitation Centre) is a designated centre, polytechnic, government college, or Anna University campus, that helps you with online registration, certificate upload, and counselling-related procedures. Registration can be done from anywhere online; visiting a TFC is optional, but it is helpful if you need assistance. There are 110+ TFCs across all 38 districts in Tamil Nadu.', 'tnea_barch_2026', true, 114),
  ('What are the working hours of TFCs?', 'All TFCs operate from 9:00 AM to 5:00 PM. Use our TFC Locator at https://neramclasses.com/counseling/tnea-barch/tfc-list to find the nearest centre, with phone numbers and address.', 'tnea_barch_2026', true, 115),
  ('How many counselling rounds are there?', 'There are 3 online counselling rounds. Each round has 4 stages: Choice Filling (3 days), Allotment, Confirmation of Allotment (2 days), and Reporting and Fee Payment (5 days). Special reservation rounds (Differently Abled, Ex-Servicemen wards, Sports Persons) happen first.', 'tnea_barch_2026', true, 116),
  ('What options do I have when a seat is allotted?', 'Six options: (1) Accept and Join, (2) Accept and Upward, (3) Decline and Upward, (4) Decline and Move to Next Round, (5) Decline and Quit, (6) Upward or Move to Next Round (shown if no seat is allotted). Non-confirmation within 2 days cancels the allotment.', 'tnea_barch_2026', true, 117),
  ('What is upward movement in TNEA?', 'Upward movement is the process where, after the main allotment, you can wait for a higher-priority choice from your preference list. You pay the necessary fee at a TFC to lock your current seat and remain in the queue for a better choice. If a better choice opens up, your previous seat is replaced; otherwise the previous seat is confirmed.', 'tnea_barch_2026', true, 118),
  ('Do scholarship holders need to pay fees during reporting?', 'No. Candidates eligible for the 7.5 percent Government School preferential quota, First Graduate scholarship, or Post-Matric Scholarship (PMSS) must report to the college or TFC but do not need to pay the fee at the time of reporting. The government / college handles the fee.', 'tnea_barch_2026', true, 119),
  ('Can persons with disabilities apply for B.Arch?', 'Yes. 5 percent horizontal reservation is available for Persons with Benchmark Disabilities. B.Arch is suitable for all 21 listed disabilities except 100 percent blindness. You need a certificate from a District Medical Board (minimum 3 doctors) in the prescribed format.', 'tnea_barch_2026', true, 120),
  ('How does the Ex-Servicemen wards quota work?', '1 seat is reserved for sons / daughters of ex-servicemen (in Stand-alone Self Finance colleges only). You need a certificate from a Tamil Nadu Department of Ex-Servicemen Welfare officer (Assistant Director or above) plus the discharge certificate and Ex-Servicemen ID card of your parent.', 'tnea_barch_2026', true, 121),
  ('How does the Sports Persons quota work?', '6 seats are reserved for Eminent Sports Persons (1 in University Department, 5 in Stand-alone Self Finance colleges). Selection is based on total marks for sports achievements per Annexure III. Sports candidates undergo in-person verification in Chennai (the only category with in-person verification).', 'tnea_barch_2026', true, 122),
  ('What happens if I do not report to the allotted college?', 'Your allotment will be cancelled and you will lose the seat. The vacant seat is pooled into the next round / upward movement. You will not be considered for further rounds in this counselling cycle.', 'tnea_barch_2026', true, 123),
  ('How many B.Arch colleges participate in TNEA?', 'Approximately 32 architecture colleges in Tamil Nadu participate, including Anna University School of Architecture and Planning (SAP), government-aided colleges, and self-financing colleges that surrender seats to TNEA. Use our College Predictor at https://app.neramclasses.com/tools/counseling/college-predictor?system=TNEA_BARCH to find colleges matching your score.', 'tnea_barch_2026', true, 124)
) AS v(question, answer, category, is_active, display_order)
WHERE NOT EXISTS (
  SELECT 1 FROM public.aintra_knowledge_base kb
  WHERE kb.question = v.question AND kb.category = v.category
);
