/**
 * Neram Classes - App Feedback Queries
 *
 * Database operations for the app feedback system (Play Store testers)
 */

import { SupabaseClient } from '@supabase/supabase-js';
import type {
  AppFeedback,
  CreateAppFeedbackInput,
  UpdateAppFeedbackInput,
  ListAppFeedbackFilters,
} from '../types';

// ============================================
// FEEDBACK OPERATIONS
// ============================================

/**
 * Create a new feedback entry
 * feedback_number is auto-generated by the DB trigger
 */
export async function createAppFeedback(
  input: CreateAppFeedbackInput,
  supabase: SupabaseClient
): Promise<AppFeedback> {
  const { data, error } = await supabase
    .from('app_feedback')
    .insert({
      feedback_number: '', // Will be auto-generated by trigger
      user_id: input.user_id || null,
      email: input.email || null,
      rating: input.rating,
      category: input.category,
      description: input.description,
      app_version: input.app_version || null,
      device_info: input.device_info || {},
      source: input.source || 'play_store',
    })
    .select()
    .single();

  if (error) throw error;
  return data;
}

/**
 * Get a feedback entry by ID
 */
export async function getAppFeedbackById(
  id: string,
  supabase: SupabaseClient
): Promise<AppFeedback | null> {
  const { data, error } = await supabase
    .from('app_feedback')
    .select('*')
    .eq('id', id)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw error;
  }
  return data;
}

/**
 * List feedback with filters and pagination (admin view)
 */
export async function listAppFeedback(
  filters: ListAppFeedbackFilters,
  supabase: SupabaseClient
): Promise<{ data: AppFeedback[]; total: number }> {
  const page = filters.page || 1;
  const limit = filters.limit || 20;
  const offset = (page - 1) * limit;

  let query = supabase
    .from('app_feedback')
    .select('*', { count: 'exact' });

  if (filters.status) {
    query = query.eq('status', filters.status);
  }

  if (filters.category) {
    query = query.eq('category', filters.category);
  }

  if (filters.rating) {
    query = query.eq('rating', filters.rating);
  }

  if (filters.search) {
    query = query.or(
      `feedback_number.ilike.%${filters.search}%,description.ilike.%${filters.search}%,email.ilike.%${filters.search}%`
    );
  }

  const { data, error, count } = await query
    .order('created_at', { ascending: false })
    .range(offset, offset + limit - 1);

  if (error) throw error;
  return { data: data || [], total: count || 0 };
}

/**
 * Update a feedback entry (admin triage)
 */
export async function updateAppFeedback(
  id: string,
  updates: UpdateAppFeedbackInput,
  supabase: SupabaseClient
): Promise<AppFeedback> {
  const { data, error } = await supabase
    .from('app_feedback')
    .update(updates)
    .eq('id', id)
    .select()
    .single();

  if (error) throw error;
  return data;
}

/**
 * Get feedback stats (for admin dashboard)
 */
export async function getAppFeedbackStats(
  supabase: SupabaseClient
): Promise<{ new_count: number; reviewed: number; in_progress: number; resolved: number; total: number; avg_rating: number }> {
  const { data, error, count } = await supabase
    .from('app_feedback')
    .select('status, rating', { count: 'exact' });

  if (error) throw error;

  const items = data || [];
  const ratings = items.map((f: { rating: number }) => f.rating);
  const avgRating = ratings.length > 0 ? ratings.reduce((a: number, b: number) => a + b, 0) / ratings.length : 0;

  return {
    new_count: items.filter((f: { status: string }) => f.status === 'new').length,
    reviewed: items.filter((f: { status: string }) => f.status === 'reviewed').length,
    in_progress: items.filter((f: { status: string }) => f.status === 'in_progress').length,
    resolved: items.filter((f: { status: string }) => f.status === 'resolved').length,
    total: count || 0,
    avg_rating: Math.round(avgRating * 10) / 10,
  };
}
