/**
 * Neram Classes - Support Ticket Queries
 *
 * Database operations for the support ticket system
 */

import { SupabaseClient } from '@supabase/supabase-js';
import type {
  SupportTicket,
  SupportTicketComment,
  CreateSupportTicketInput,
  UpdateSupportTicketInput,
  ListSupportTicketsFilters,
} from '../types';

// ============================================
// TICKET OPERATIONS
// ============================================

/**
 * Create a new support ticket
 * ticket_number is auto-generated by the DB trigger
 */
export async function createSupportTicket(
  input: CreateSupportTicketInput,
  supabase: SupabaseClient
): Promise<SupportTicket> {
  const { data, error } = await supabase
    .from('support_tickets')
    .insert({
      ticket_number: '', // Will be auto-generated by trigger
      user_id: input.user_id || null,
      user_name: input.user_name,
      user_email: input.user_email || null,
      user_phone: input.user_phone || null,
      category: input.category,
      subject: input.subject,
      description: input.description,
      page_url: input.page_url || null,
      source_app: input.source_app || null,
      enrollment_link_id: input.enrollment_link_id || null,
      screenshot_urls: input.screenshot_urls || [],
    })
    .select()
    .single();

  if (error) throw error;
  return data;
}

/**
 * Get a support ticket by ID
 */
export async function getSupportTicketById(
  id: string,
  supabase: SupabaseClient
): Promise<SupportTicket | null> {
  const { data, error } = await supabase
    .from('support_tickets')
    .select('*')
    .eq('id', id)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw error;
  }
  return data;
}

/**
 * Get a support ticket by ticket number
 */
export async function getSupportTicketByNumber(
  ticketNumber: string,
  supabase: SupabaseClient
): Promise<SupportTicket | null> {
  const { data, error } = await supabase
    .from('support_tickets')
    .select('*')
    .eq('ticket_number', ticketNumber)
    .single();

  if (error) {
    if (error.code === 'PGRST116') return null;
    throw error;
  }
  return data;
}

/**
 * List support tickets with filters and pagination (admin view)
 */
export async function listSupportTickets(
  filters: ListSupportTicketsFilters,
  supabase: SupabaseClient
): Promise<{ data: SupportTicket[]; total: number }> {
  const page = filters.page || 1;
  const limit = filters.limit || 20;
  const offset = (page - 1) * limit;

  let query = supabase
    .from('support_tickets')
    .select('*', { count: 'exact' });

  if (filters.status) {
    query = query.eq('status', filters.status);
  }

  if (filters.category) {
    query = query.eq('category', filters.category);
  }

  if (filters.userId) {
    query = query.eq('user_id', filters.userId);
  }

  if (filters.search) {
    query = query.or(
      `ticket_number.ilike.%${filters.search}%,user_name.ilike.%${filters.search}%,user_email.ilike.%${filters.search}%,subject.ilike.%${filters.search}%`
    );
  }

  const { data, error, count } = await query
    .order('created_at', { ascending: false })
    .range(offset, offset + limit - 1);

  if (error) throw error;
  return { data: data || [], total: count || 0 };
}

/**
 * List tickets for a specific user
 */
export async function listUserTickets(
  userId: string,
  filters: Omit<ListSupportTicketsFilters, 'userId'>,
  supabase: SupabaseClient
): Promise<{ data: SupportTicket[]; total: number }> {
  return listSupportTickets({ ...filters, userId }, supabase);
}

/**
 * Update a support ticket
 */
export async function updateSupportTicket(
  id: string,
  updates: UpdateSupportTicketInput,
  supabase: SupabaseClient
): Promise<SupportTicket> {
  const { data, error } = await supabase
    .from('support_tickets')
    .update(updates)
    .eq('id', id)
    .select()
    .single();

  if (error) throw error;
  return data;
}

// ============================================
// COMMENT OPERATIONS
// ============================================

/**
 * Add a comment to a ticket
 */
export async function addTicketComment(
  input: {
    ticket_id: string;
    user_id?: string;
    user_name: string;
    is_admin: boolean;
    content: string;
  },
  supabase: SupabaseClient
): Promise<SupportTicketComment> {
  const { data, error } = await supabase
    .from('support_ticket_comments')
    .insert({
      ticket_id: input.ticket_id,
      user_id: input.user_id || null,
      user_name: input.user_name,
      is_admin: input.is_admin,
      content: input.content,
    })
    .select()
    .single();

  if (error) throw error;
  return data;
}

/**
 * Get comments for a ticket
 */
export async function getTicketComments(
  ticketId: string,
  supabase: SupabaseClient
): Promise<SupportTicketComment[]> {
  const { data, error } = await supabase
    .from('support_ticket_comments')
    .select('*')
    .eq('ticket_id', ticketId)
    .order('created_at', { ascending: true });

  if (error) throw error;
  return data || [];
}

// ============================================
// STATS
// ============================================

/**
 * Get ticket count by status (for admin dashboard stats)
 */
export async function getSupportTicketStats(
  supabase: SupabaseClient
): Promise<{ open: number; in_progress: number; resolved: number; total: number }> {
  const { data, error, count } = await supabase
    .from('support_tickets')
    .select('status', { count: 'exact' });

  if (error) throw error;

  const statuses = data || [];
  return {
    open: statuses.filter((t: { status: string }) => t.status === 'open').length,
    in_progress: statuses.filter((t: { status: string }) => t.status === 'in_progress').length,
    resolved: statuses.filter((t: { status: string }) => t.status === 'resolved').length,
    total: count || 0,
  };
}
