import type { NexusQBQuestion } from '@neram/database';

// ============================================
// Answer Key JSON Schema — generated by AI tools
// ============================================

export interface AnswerKeyJSON {
  schema_version: '1.0';
  paper: {
    exam_name: string;
    exam_date?: string;
  };
  answers: AnswerKeyEntry[];
}

export interface AnswerKeyEntry {
  /** NTA QuestionID (matches nta_question_id on questions) */
  question_id: string;
  /** NTA correct option ID (for MCQ — matches nta_id on options) */
  correct_option_id?: string;
  /** Numeric answer value (for NUMERICAL questions) */
  correct_value?: string;
  /** Dropped questions */
  status?: 'valid' | 'dropped';
}

// ============================================
// Match result for preview
// ============================================

export interface AnswerKeyMatch {
  questionNumber: number;
  ntaQuestionId: string;
  questionFormat: string;
  resolvedAnswer: string;
  matchedOptionLabel: string;
  status: 'matched' | 'not_found' | 'option_not_found' | 'dropped' | 'numerical';
  warning?: string;
}

export interface AnswerKeyMatchResult {
  matches: AnswerKeyMatch[];
  summary: {
    total: number;
    matched: number;
    notFound: number;
    optionNotFound: number;
    dropped: number;
    numerical: number;
  };
}

// ============================================
// Validation
// ============================================

export interface AnswerKeyValidation {
  valid: boolean;
  errors: string[];
  warnings: string[];
  data?: AnswerKeyJSON;
}

export function validateAnswerKeyJSON(raw: unknown): AnswerKeyValidation {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!raw || typeof raw !== 'object') {
    return { valid: false, errors: ['Invalid JSON: expected an object'], warnings };
  }

  const json = raw as Record<string, unknown>;

  if (json.schema_version !== '1.0') {
    warnings.push(`Unknown schema_version "${json.schema_version}", attempting to parse anyway`);
  }

  if (!json.paper || typeof json.paper !== 'object') {
    warnings.push('Missing "paper" metadata — not critical');
  }

  const answers = json.answers;
  if (!Array.isArray(answers) || answers.length === 0) {
    errors.push('Missing or empty "answers" array');
    return { valid: false, errors, warnings };
  }

  for (let i = 0; i < answers.length; i++) {
    const entry = answers[i] as Record<string, unknown>;
    if (!entry.question_id || typeof entry.question_id !== 'string') {
      errors.push(`Answer #${i + 1}: missing "question_id"`);
    }

    const isDropped = entry.status === 'dropped';
    const hasMcqAnswer = entry.correct_option_id && typeof entry.correct_option_id === 'string';
    const hasNumericalAnswer = entry.correct_value !== undefined && entry.correct_value !== null;

    if (!isDropped && !hasMcqAnswer && !hasNumericalAnswer) {
      warnings.push(
        `Answer #${i + 1} (${entry.question_id}): no correct_option_id, correct_value, or dropped status`
      );
    }
  }

  if (errors.length > 0) {
    return { valid: false, errors, warnings };
  }

  return {
    valid: true,
    errors,
    warnings,
    data: raw as AnswerKeyJSON,
  };
}

// ============================================
// Matching — resolve NTA IDs to internal IDs
// ============================================

export function matchAnswerKeyToQuestions(
  answerKey: AnswerKeyJSON,
  questions: NexusQBQuestion[],
): AnswerKeyMatchResult {
  // Build lookup: nta_question_id → question
  const questionByNtaId = new Map<string, NexusQBQuestion>();
  for (const q of questions) {
    if (q.nta_question_id) {
      questionByNtaId.set(q.nta_question_id, q);
    }
  }

  const matches: AnswerKeyMatch[] = [];
  let matched = 0;
  let notFound = 0;
  let optionNotFound = 0;
  let dropped = 0;
  let numerical = 0;

  for (const entry of answerKey.answers) {
    const question = questionByNtaId.get(entry.question_id);

    // Dropped question
    if (entry.status === 'dropped') {
      dropped++;
      matches.push({
        questionNumber: question?.display_order ?? 0,
        ntaQuestionId: entry.question_id,
        questionFormat: question?.question_format ?? 'unknown',
        resolvedAnswer: 'dropped',
        matchedOptionLabel: 'Dropped',
        status: 'dropped',
      });
      continue;
    }

    // Question not found in paper
    if (!question) {
      notFound++;
      matches.push({
        questionNumber: 0,
        ntaQuestionId: entry.question_id,
        questionFormat: 'unknown',
        resolvedAnswer: '',
        matchedOptionLabel: '',
        status: 'not_found',
        warning: `Question with NTA ID "${entry.question_id}" not found in this paper`,
      });
      continue;
    }

    const qNum = question.display_order ?? 0;

    // NUMERICAL question — use correct_value directly
    if (entry.correct_value !== undefined && entry.correct_value !== null) {
      numerical++;
      matches.push({
        questionNumber: qNum,
        ntaQuestionId: entry.question_id,
        questionFormat: question.question_format,
        resolvedAnswer: String(entry.correct_value),
        matchedOptionLabel: `Value: ${entry.correct_value}`,
        status: 'numerical',
      });
      continue;
    }

    // MCQ question — resolve option NTA ID to internal ID (a/b/c/d)
    if (entry.correct_option_id && question.options) {
      const matchedOption = question.options.find(
        (opt) => opt.nta_id === entry.correct_option_id
      );

      if (matchedOption) {
        matched++;
        matches.push({
          questionNumber: qNum,
          ntaQuestionId: entry.question_id,
          questionFormat: question.question_format,
          resolvedAnswer: matchedOption.id,
          matchedOptionLabel: `Option ${matchedOption.id.toUpperCase()}`,
          status: 'matched',
        });
      } else {
        optionNotFound++;
        matches.push({
          questionNumber: qNum,
          ntaQuestionId: entry.question_id,
          questionFormat: question.question_format,
          resolvedAnswer: '',
          matchedOptionLabel: '',
          status: 'option_not_found',
          warning: `Option NTA ID "${entry.correct_option_id}" not found in Q${qNum} options`,
        });
      }
      continue;
    }

    // Fallback — no answer data
    notFound++;
    matches.push({
      questionNumber: qNum,
      ntaQuestionId: entry.question_id,
      questionFormat: question.question_format,
      resolvedAnswer: '',
      matchedOptionLabel: '',
      status: 'not_found',
      warning: 'No correct_option_id or correct_value provided',
    });
  }

  // Sort by question number
  matches.sort((a, b) => a.questionNumber - b.questionNumber);

  return {
    matches,
    summary: { total: answerKey.answers.length, matched, notFound, optionNotFound, dropped, numerical },
  };
}

// ============================================
// Example JSON + AI Prompt Template
// ============================================

export const ANSWER_KEY_JSON_EXAMPLE: AnswerKeyJSON = {
  schema_version: '1.0',
  paper: {
    exam_name: 'JEE Paper 2 (B.Arch) - January 2025',
    exam_date: '2025-01-25',
  },
  answers: [
    { question_id: '4951349335', correct_option_id: '49513493352' },
    { question_id: '4951349336', correct_option_id: '49513493364' },
    { question_id: '4951349355', correct_value: '42' },
    { question_id: '4951349400', status: 'dropped' },
  ],
};

export const ANSWER_KEY_AI_PROMPT = `I have an NTA official answer key (it may be a PDF, image, or table). Please extract the answer data and output it as JSON matching this exact schema:

\`\`\`json
${JSON.stringify(ANSWER_KEY_JSON_EXAMPLE, null, 2)}
\`\`\`

Rules:
1. Output ONLY valid JSON, no extra text.
2. Use "schema_version": "1.0".
3. Extract exam_name and exam_date from the document header if available.
4. For each row in the answer key:
   - "question_id": The NTA QuestionID (the long numeric string, e.g. "4951349335")
   - For MCQ questions: "correct_option_id" should be the NTA Option ID of the correct answer (e.g. "49513493352")
   - For Numerical questions: "correct_value" should be the numeric answer as a string (e.g. "42")
   - For dropped/cancelled questions: set "status": "dropped"
5. Do NOT include the S.No or Section columns — only question_id and the correct answer.
6. The question_id and correct_option_id are the long numeric IDs from the NTA system, NOT the question number (1, 2, 3...).

Here is the answer key:`;
