/**
 * Creating a student's Microsoft account from Nexus, start to finish, and
 * resetting its password later.
 *
 * The order is the point:
 *
 *   1. Ask before creating. If the details look like a student Nexus already has
 *      (same phone, same email, a similar name in this class), stop and ask, the
 *      same question adding an existing account asks. A second record for one
 *      student is how Afrin ended up twice on the roster.
 *   2. Create the Microsoft account. Nothing else happens if this fails.
 *   3. License it. A failure keeps the account: the student can still sign in,
 *      and deleting a half-made account would throw away the login we are about
 *      to hand over.
 *   4. Attach it to the student's record (the one staff picked, or the one the
 *      reconciler recognises), or create the record. Never a duplicate.
 *   5. Enroll them in this class and set their class and exam year.
 *   6. Add them to the class Team, best effort: a new mailbox can take minutes.
 *
 * Graph and the database sit behind ports so this ordering is tested without
 * either. The password is generated by the caller and returned once; nothing in
 * this module writes it anywhere, including the audit trail.
 */

import type { GraphErrorInfo } from '@neram/auth';
import type { CreateEntraUserInput, GraphResult } from './entra-accounts';
import type { IdentityCandidate } from './identity-candidates';
import { isValidUsername, normalizeIndianMobile, upnFor } from './student-account-rules';

export interface AccountGraphPort {
  isUpnAvailable(upn: string): Promise<GraphResult<boolean>>;
  createUser(input: CreateEntraUserInput): Promise<GraphResult<{ id: string }>>;
  assignLicense(userId: string, skuId: string): Promise<GraphResult<void>>;
  addToGroup(groupId: string, userId: string): Promise<GraphResult<void>>;
  setOtherMails(userId: string, emails: string[]): Promise<GraphResult<void>>;
}

export interface StudentRecord {
  id: string;
  name: string | null;
  first_name: string | null;
  ms_oid: string | null;
  user_type: string | null;
  staff_role: string | null;
  phone: string | null;
  email: string | null;
  personal_email: string | null;
}

export type TeamsSyncOutcome =
  | { status: 'done' }
  | { status: 'skipped'; reason: string }
  | { status: 'failed'; reason: string };

export interface AccountStorePort {
  getStudent(userId: string): Promise<StudentRecord | null>;
  findCandidates(input: {
    classroomId: string;
    name: string;
    phone: string | null;
    personalEmail: string | null;
  }): Promise<IdentityCandidate[]>;
  linkMicrosoft(userId: string, msOid: string, upn: string, actorId: string): Promise<void>;
  /** The reconciler with creation allowed: an existing match is attached, otherwise a record is made. */
  createOrMatchRecord(input: {
    msOid: string;
    upn: string;
    name: string;
    phoneHints: string[];
    emailHints: string[];
  }): Promise<string | null>;
  /** Fills blanks only; never overwrites what a record already holds. */
  fillContact(
    userId: string,
    contact: { firstName: string; lastName: string; phone: string | null; personalEmail: string | null },
  ): Promise<void>;
  enroll(input: { userId: string; classroomId: string; batchId: string | null }): Promise<void>;
  classify(input: {
    userId: string;
    classroomId: string;
    studyStage: string | null;
    academicYear: string | null;
    actorId: string;
  }): Promise<void>;
  syncTeams(input: { userId: string; classroomId: string; upn: string }): Promise<TeamsSyncOutcome>;
  audit(userId: string, field: string, value: unknown, actorId: string): Promise<void>;
}

export interface StudentLicenseChoice {
  skuId: string;
  mode: 'direct' | 'group';
  groupId: string | null;
}

export interface CreateStudentAccountInput {
  classroomId: string;
  firstName: string;
  lastName: string;
  username: string;
  domain: string;
  usageLocation: string;
  /** Ten digits, already normalised. */
  phone: string | null;
  personalEmail: string | null;
  studyStage: string | null;
  academicYear: string | null;
  batchId: string | null;
  /** The student record staff said this account is for. */
  attachToUserId: string | null;
  /** Staff already answered "a different student" to the duplicate question. */
  confirmNew: boolean;
  license: StudentLicenseChoice | null;
  password: string;
  actorId: string;
}

export type StepStatus = 'done' | 'failed' | 'skipped';

export interface StepState {
  status: StepStatus;
  message?: string;
}

export interface AccountSteps {
  account: StepState;
  license: StepState;
  record: StepState;
  classroom: StepState;
  teams: StepState;
}

export type ConflictCode = 'record_missing' | 'not_a_student' | 'already_linked' | 'upn_taken' | 'no_microsoft';

export type CreateStudentAccountResult =
  | { kind: 'invalid'; status: 400; error: string }
  | { kind: 'conflict'; status: 404 | 409; code: ConflictCode; error: string }
  | { kind: 'possible_duplicate'; status: 409; candidates: IdentityCandidate[] }
  | { kind: 'graph_failed'; status: number; error: GraphErrorInfo }
  | {
      kind: 'created';
      upn: string;
      password: string;
      msOid: string;
      userId: string | null;
      firstName: string;
      phone: string | null;
      steps: AccountSteps;
    };

export const UPN_TAKEN =
  'That login ID is already taken. Choose another. If you just created it, the student is listed under Existing Microsoft account.';
export const RECORD_MISSING = 'That student record no longer exists. Refresh and try again.';
export const NOT_A_STUDENT = 'Microsoft accounts can only be created or reset here for students.';
export const ALREADY_LINKED = 'This student already has a Microsoft account. Use Reset password instead.';
export const NO_MICROSOFT = 'This student has no Microsoft account yet. Create one first.';
export const NO_LICENSE = 'No student license is set up, so the account has none yet.';
export const RECORD_FAILED =
  'The Microsoft account was created, but Nexus could not save the student record. Add them from Existing Microsoft account.';
export const CLASSROOM_FAILED = 'Could not add them to this class. Add them from Existing Microsoft account.';
export const CLASSIFY_FAILED = 'Added to the class, but the class and exam year were not saved. Set them from the roster.';
export const TEAMS_FAILED =
  'Not in the class Team yet. A brand new account can take a few minutes to reach Microsoft Teams.';

const STAFF_TYPES = new Set(['admin', 'teacher']);
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function isStaffRecord(record: StudentRecord): boolean {
  return !!record.staff_role || STAFF_TYPES.has(String(record.user_type || ''));
}

function describe(error: GraphErrorInfo): string {
  return error.fix ? `${error.message} ${error.fix}` : error.message;
}

export async function createStudentAccount(
  graph: AccountGraphPort,
  store: AccountStorePort,
  input: CreateStudentAccountInput,
): Promise<CreateStudentAccountResult> {
  const firstName = input.firstName.trim();
  const lastName = input.lastName.trim();
  if (!firstName) return { kind: 'invalid', status: 400, error: 'First name is required.' };
  if (!isValidUsername(input.username)) {
    return {
      kind: 'invalid',
      status: 400,
      error: 'The login ID can use letters, numbers, dots, dashes and underscores, and must start and end with a letter or number.',
    };
  }
  if (input.personalEmail && !EMAIL.test(input.personalEmail)) {
    return { kind: 'invalid', status: 400, error: 'That personal email does not look right.' };
  }

  const displayName = [firstName, lastName].filter(Boolean).join(' ');
  const upn = upnFor(input.username, input.domain);

  // 1. Whose account is this?
  let target: StudentRecord | null = null;
  if (input.attachToUserId) {
    target = await store.getStudent(input.attachToUserId);
    if (!target) return { kind: 'conflict', status: 404, code: 'record_missing', error: RECORD_MISSING };
    if (isStaffRecord(target)) return { kind: 'conflict', status: 409, code: 'not_a_student', error: NOT_A_STUDENT };
    if (target.ms_oid) return { kind: 'conflict', status: 409, code: 'already_linked', error: ALREADY_LINKED };
  } else if (!input.confirmNew) {
    const candidates = await store.findCandidates({
      classroomId: input.classroomId,
      name: displayName,
      phone: input.phone,
      personalEmail: input.personalEmail,
    });
    if (candidates.length) return { kind: 'possible_duplicate', status: 409, candidates };
  }

  // 2. The Microsoft account.
  const available = await graph.isUpnAvailable(upn);
  if (!available.ok) return { kind: 'graph_failed', status: available.status || 502, error: available.error };
  if (!available.value) return { kind: 'conflict', status: 409, code: 'upn_taken', error: UPN_TAKEN };

  const created = await graph.createUser({
    displayName,
    givenName: firstName,
    surname: lastName || null,
    upn,
    mailNickname: input.username,
    password: input.password,
    mobilePhone: input.phone ? `+91 ${input.phone}` : null,
    usageLocation: input.usageLocation,
  });
  if (!created.ok) {
    if (/already exists/i.test(created.error.raw || '')) {
      return { kind: 'conflict', status: 409, code: 'upn_taken', error: UPN_TAKEN };
    }
    return { kind: 'graph_failed', status: created.status || 502, error: created.error };
  }
  const msOid = created.value.id;

  const steps: AccountSteps = {
    account: { status: 'done' },
    license: { status: 'skipped', message: NO_LICENSE },
    record: { status: 'skipped' },
    classroom: { status: 'skipped' },
    teams: { status: 'skipped' },
  };

  // 3. The license. A failure keeps the account.
  if (input.license) {
    const licensed =
      input.license.mode === 'group' && input.license.groupId
        ? await graph.addToGroup(input.license.groupId, msOid)
        : await graph.assignLicense(msOid, input.license.skuId);
    steps.license = licensed.ok ? { status: 'done' } : { status: 'failed', message: describe(licensed.error) };
  }

  // The personal email on the Microsoft account helps every later match. Best effort.
  if (input.personalEmail) await graph.setOtherMails(msOid, [input.personalEmail]);

  // 4. The student record: the one staff picked, the one the reconciler knows, or a new one.
  let userId: string | null = null;
  try {
    if (target) {
      await store.linkMicrosoft(target.id, msOid, upn, input.actorId);
      userId = target.id;
    } else {
      // Staff said "a different student", so the phone and email must not pull
      // this account onto the record they just rejected.
      userId = await store.createOrMatchRecord({
        msOid,
        upn,
        name: displayName,
        phoneHints: !input.confirmNew && input.phone ? [input.phone] : [],
        emailHints: !input.confirmNew && input.personalEmail ? [input.personalEmail] : [],
      });
    }
  } catch {
    userId = null;
  }
  if (!userId) {
    steps.record = { status: 'failed', message: RECORD_FAILED };
    return { kind: 'created', upn, password: input.password, msOid, userId: null, firstName, phone: input.phone, steps };
  }
  steps.record = { status: 'done' };

  try {
    await store.fillContact(userId, { firstName, lastName, phone: input.phone, personalEmail: input.personalEmail });
  } catch {
    // Contact details are a convenience; the record and the account already exist.
  }

  // 5. This class, then their class and exam year.
  try {
    await store.enroll({ userId, classroomId: input.classroomId, batchId: input.batchId });
    steps.classroom = { status: 'done' };
  } catch {
    steps.classroom = { status: 'failed', message: CLASSROOM_FAILED };
  }
  if (steps.classroom.status === 'done' && (input.studyStage || input.academicYear)) {
    try {
      await store.classify({
        userId,
        classroomId: input.classroomId,
        studyStage: input.studyStage,
        academicYear: input.academicYear,
        actorId: input.actorId,
      });
    } catch {
      steps.classroom = { status: 'done', message: CLASSIFY_FAILED };
    }
  }

  // 6. The class Team.
  if (steps.classroom.status === 'done') {
    try {
      const teams = await store.syncTeams({ userId, classroomId: input.classroomId, upn });
      steps.teams = teams.status === 'done' ? { status: 'done' } : { status: teams.status, message: teams.reason };
    } catch {
      steps.teams = { status: 'failed', message: TEAMS_FAILED };
    }
  }

  // The audit names the account and the license. Never the password.
  try {
    await store.audit(userId, 'microsoft_account', { upn, license: input.license?.skuId ?? null }, input.actorId);
  } catch {
    // An audit failure must not undo an account staff are about to hand over.
  }

  return { kind: 'created', upn, password: input.password, msOid, userId, firstName, phone: input.phone, steps };
}

// ── Reset password ──────────────────────────────────────────────────────────

export interface ResetPasswordPorts {
  getStudent(userId: string): Promise<StudentRecord | null>;
  resetPassword(msOid: string, password: string): Promise<GraphResult<void>>;
  readUpn(msOid: string): Promise<GraphResult<string>>;
  audit(userId: string, field: string, value: unknown, actorId: string): Promise<void>;
}

export type ResetStudentPasswordResult =
  | { kind: 'conflict'; status: 404 | 409; code: ConflictCode; error: string }
  | { kind: 'graph_failed'; status: number; error: GraphErrorInfo }
  | { kind: 'reset'; upn: string; password: string; firstName: string; phone: string | null };

export async function resetStudentPassword(
  ports: ResetPasswordPorts,
  input: { userId: string; password: string; actorId: string },
): Promise<ResetStudentPasswordResult> {
  const record = await ports.getStudent(input.userId);
  if (!record) return { kind: 'conflict', status: 404, code: 'record_missing', error: RECORD_MISSING };
  // Staff passwords are managed in Azure, never from a student screen.
  if (isStaffRecord(record)) return { kind: 'conflict', status: 409, code: 'not_a_student', error: NOT_A_STUDENT };
  if (!record.ms_oid) return { kind: 'conflict', status: 409, code: 'no_microsoft', error: NO_MICROSOFT };

  const reset = await ports.resetPassword(record.ms_oid, input.password);
  if (!reset.ok) return { kind: 'graph_failed', status: reset.status || 502, error: reset.error };

  const upnResult = await ports.readUpn(record.ms_oid);
  const upn = upnResult.ok && upnResult.value ? upnResult.value : record.email || '';

  try {
    await ports.audit(record.id, 'microsoft_password_reset', { upn }, input.actorId);
  } catch {
    // The reset happened; a missing audit row must not hide the new password.
  }

  return {
    kind: 'reset',
    upn,
    password: input.password,
    firstName: record.first_name || (record.name || '').split(' ')[0] || '',
    phone: normalizeIndianMobile(record.phone),
  };
}
