-- Add unified student_id to student_profiles
-- Format: NRM-YYMM-NNNNN (e.g., NRM-2603-00001)
-- Auto-generated by DB trigger on INSERT, shared sequence across all enrollment flows

-- 1. Add student_id column
ALTER TABLE student_profiles
ADD COLUMN IF NOT EXISTS student_id TEXT UNIQUE;

-- 2. Create sequence
CREATE SEQUENCE IF NOT EXISTS student_id_seq START 1;

-- 3. Trigger function: auto-generate student_id on INSERT
CREATE OR REPLACE FUNCTION generate_student_id()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.student_id IS NULL THEN
    NEW.student_id := 'NRM-' || TO_CHAR(NOW(), 'YYMM') || '-' ||
                       LPAD(NEXTVAL('student_id_seq')::TEXT, 5, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER generate_student_id_trigger
BEFORE INSERT ON student_profiles
FOR EACH ROW
EXECUTE FUNCTION generate_student_id();

-- 4. Backfill existing student_profiles that have no student_id
UPDATE student_profiles
SET student_id = 'NRM-' || TO_CHAR(created_at, 'YYMM') || '-' ||
                 LPAD(NEXTVAL('student_id_seq')::TEXT, 5, '0')
WHERE student_id IS NULL;
