-- ============================================
-- WHEN THE STUDENTS WERE TOLD THIS RECAP WAS READY
--
-- One nullable timestamp, used as a CLAIM rather than as a record.
--
-- The announcement is sent from the post-class sweep, which now runs every
-- fifteen minutes instead of twice a night. Three things follow from that, and
-- each of them would double-message a student without this column:
--
--   * two runs can overlap, because a slow Graph call makes one pass outlast its
--     own schedule;
--   * a recap taken down and regenerated by the repair rule is published a
--     second time, and its students have already been told;
--   * `auto_published_at` is rewritten on every publish, so it cannot answer
--     "has anyone been told about this one".
--
-- Claimed the way `join_reminders_sent` and `nexus_sketchbook_reminders` are:
-- the writer stamps it with `.is('students_notified_at', null)` in the predicate
-- and only sends when the update actually matched a row. A claim that loses the
-- race matches nothing and sends nothing.
--
-- Deliberately NOT cleared by `unpublishForRepair`. A student told once about a
-- class does not need telling again because the checkpoints were rebuilt, and a
-- repair is invisible to them.
-- ============================================

ALTER TABLE nexus_class_recaps
  ADD COLUMN IF NOT EXISTS students_notified_at TIMESTAMPTZ;

COMMENT ON COLUMN nexus_class_recaps.students_notified_at IS
  'Claim stamp for the one "your catch-up is ready" message. Set before sending, never cleared.';

-- Every recap that existed before this column did. Backfilled as ALREADY TOLD,
-- which is the safe direction: these classes are between one and three months
-- old, their students have long since caught up or been chased about them, and
-- announcing thirty-four of them in one sweep would arrive as a wall of Teams
-- messages about lessons nobody is waiting on.
UPDATE nexus_class_recaps
   SET students_notified_at = COALESCE(published_at, updated_at, created_at)
 WHERE students_notified_at IS NULL
   AND status = 'published';
